### ISSUE TITLE
Bw64Reader tell() returns incorrect position

### ISSUE THREAD

**Issue by rsjbailey** [ebu/libbw64#3]
The tell() function at line 253 of reader.hpp is supposed to return the current read position in the data chunk in terms of frames. It calculates this by subtracting the position of the data chunk from the read position in the file, dividing the result by the block alignment. 

The data samples actually start at the data chunk position +8 bytes (4 for the chunk ID and 4 for the chunk size), so the value returned by tell() is slightly farther along the file than the actual position.

The effect of this is that the last couple of samples are skipped when reading a file as the sanity checking code on line 238 gets an incorrect position from tell().

The following test  exposes the issue

```c++
#include <array>
BOOST_AUTO_TEST_CASE(can_read_all_frames) {
  Bw64Reader bw64File("testfiles/noise_24bit_uneven_data_chunk_size.wav");
  BOOST_TEST(bw64File.numberOfFrames() == 13);
  std::array<float, 13> readBuffer;
  int readSampleCount = bw64File.read(readBuffer.data(), 13);
  BOOST_TEST(readSampleCount == 13);
}
```

**Comment by benjamin-weiss** [comment]
Thanks a lot Richard. I just made a pull request which should fix this. The PR also addresses the other issue you reported.
