### ISSUE TITLE
Handle AXML chunk > 4GB

### ISSUE THREAD

**Issue by mzed** [ebu/libbw64#48]
This "TODO:" comment sums it up: https://github.com/ebu/libbw64/blob/master/include/bw64/writer.hpp#:~:text=//%20TODO%3A%20add%20other%20chunks%20which%20are%20bigger%20than%204GB

If the AXML chunk is bigger than 4 GB, that isn't being added to the ds64 chunk as it needs to be.

**Comment by mprevot** [comment]
I wonder: is there any mainenance or the project is meant to die after they got their H2020 grant ?

**Comment by tomjnixon** [comment]
Thank you for the sarcastic comment.
